package com.community.mapper;

import com.community.model.Question;
import com.community.model.QuestionExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface QuestionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    long countByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int deleteByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int insert(Question row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int insertSelective(Question row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    List<Question> selectByExampleWithRowbounds(QuestionExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    List<Question> selectByExample(QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    Question selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int updateByExampleSelective(@Param("row") Question row, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int updateByExample(@Param("row") Question row, @Param("example") QuestionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int updateByPrimaryKeySelective(Question row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    int updateByPrimaryKey(Question row);
}