package com.community.mapper;

import com.community.model.Star;
import com.community.model.StarExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface StarMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    long countByExample(StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int deleteByExample(StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int insert(Star row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int insertSelective(Star row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    List<Star> selectByExampleWithRowbounds(StarExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    List<Star> selectByExample(StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    Star selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int updateByExampleSelective(@Param("row") Star row, @Param("example") StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int updateByExample(@Param("row") Star row, @Param("example") StarExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int updateByPrimaryKeySelective(Star row);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table star_record
     *
     * @mbg.generated Fri May 13 21:29:48 CST 2022
     */
    int updateByPrimaryKey(Star row);
}