package com.community.model;

public class Like {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.target_id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column like_record.like_creator
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String likeCreator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.id
     *
     * @return the value of like_record.id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.id
     *
     * @param id the value for like_record.id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.target_id
     *
     * @return the value of like_record.target_id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.target_id
     *
     * @param targetId the value for like_record.target_id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.gmt_create
     *
     * @return the value of like_record.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.gmt_create
     *
     * @param gmtCreate the value for like_record.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.gmt_modified
     *
     * @return the value of like_record.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.gmt_modified
     *
     * @param gmtModified the value for like_record.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column like_record.like_creator
     *
     * @return the value of like_record.like_creator
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getLikeCreator() {
        return likeCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column like_record.like_creator
     *
     * @param likeCreator the value for like_record.like_creator
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setLikeCreator(String likeCreator) {
        this.likeCreator = likeCreator == null ? null : likeCreator.trim();
    }
}