package com.community.model;

public class Like {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_RECORD.ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_RECORD.TARGET_ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_RECORD.GMT_CREATE
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_RECORD.GMT_MODIFIED
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column LIKE_RECORD.LIKE_CREATOR
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private String likeCreator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_RECORD.ID
     *
     * @return the value of LIKE_RECORD.ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_RECORD.ID
     *
     * @param id the value for LIKE_RECORD.ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_RECORD.TARGET_ID
     *
     * @return the value of LIKE_RECORD.TARGET_ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_RECORD.TARGET_ID
     *
     * @param targetId the value for LIKE_RECORD.TARGET_ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_RECORD.GMT_CREATE
     *
     * @return the value of LIKE_RECORD.GMT_CREATE
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_RECORD.GMT_CREATE
     *
     * @param gmtCreate the value for LIKE_RECORD.GMT_CREATE
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_RECORD.GMT_MODIFIED
     *
     * @return the value of LIKE_RECORD.GMT_MODIFIED
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_RECORD.GMT_MODIFIED
     *
     * @param gmtModified the value for LIKE_RECORD.GMT_MODIFIED
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column LIKE_RECORD.LIKE_CREATOR
     *
     * @return the value of LIKE_RECORD.LIKE_CREATOR
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public String getLikeCreator() {
        return likeCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column LIKE_RECORD.LIKE_CREATOR
     *
     * @param likeCreator the value for LIKE_RECORD.LIKE_CREATOR
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setLikeCreator(String likeCreator) {
        this.likeCreator = likeCreator == null ? null : likeCreator.trim();
    }
}