package com.community.model;

public class Question {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.title
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String title;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.description
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String description;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.creator
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String creator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.comment_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long commentCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.view_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long viewCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.like_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long likeCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.tag
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String tag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.star_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long starCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column question.sticky
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Integer sticky;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.id
     *
     * @return the value of question.id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.id
     *
     * @param id the value for question.id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.title
     *
     * @return the value of question.title
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.title
     *
     * @param title the value for question.title
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setTitle(String title) {
        this.title = title == null ? null : title.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.description
     *
     * @return the value of question.description
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.description
     *
     * @param description the value for question.description
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setDescription(String description) {
        this.description = description == null ? null : description.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_create
     *
     * @return the value of question.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_create
     *
     * @param gmtCreate the value for question.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.gmt_modified
     *
     * @return the value of question.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.gmt_modified
     *
     * @param gmtModified the value for question.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.creator
     *
     * @return the value of question.creator
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.creator
     *
     * @param creator the value for question.creator
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.comment_count
     *
     * @return the value of question.comment_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getCommentCount() {
        return commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.comment_count
     *
     * @param commentCount the value for question.comment_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setCommentCount(Long commentCount) {
        this.commentCount = commentCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.view_count
     *
     * @return the value of question.view_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getViewCount() {
        return viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.view_count
     *
     * @param viewCount the value for question.view_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setViewCount(Long viewCount) {
        this.viewCount = viewCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.like_count
     *
     * @return the value of question.like_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getLikeCount() {
        return likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.like_count
     *
     * @param likeCount the value for question.like_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setLikeCount(Long likeCount) {
        this.likeCount = likeCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.tag
     *
     * @return the value of question.tag
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getTag() {
        return tag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.tag
     *
     * @param tag the value for question.tag
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setTag(String tag) {
        this.tag = tag == null ? null : tag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.star_count
     *
     * @return the value of question.star_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getStarCount() {
        return starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.star_count
     *
     * @param starCount the value for question.star_count
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setStarCount(Long starCount) {
        this.starCount = starCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column question.sticky
     *
     * @return the value of question.sticky
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Integer getSticky() {
        return sticky;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column question.sticky
     *
     * @param sticky the value for question.sticky
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setSticky(Integer sticky) {
        this.sticky = sticky;
    }
}