package com.community.model;

public class Star {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_RECORD.ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_RECORD.TARGET_ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long targetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_RECORD.GMT_CREATE
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_RECORD.GMT_MODIFIED
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column STAR_RECORD.STAR_CREATOR
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    private String starCreator;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_RECORD.ID
     *
     * @return the value of STAR_RECORD.ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_RECORD.ID
     *
     * @param id the value for STAR_RECORD.ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_RECORD.TARGET_ID
     *
     * @return the value of STAR_RECORD.TARGET_ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getTargetId() {
        return targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_RECORD.TARGET_ID
     *
     * @param targetId the value for STAR_RECORD.TARGET_ID
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setTargetId(Long targetId) {
        this.targetId = targetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_RECORD.GMT_CREATE
     *
     * @return the value of STAR_RECORD.GMT_CREATE
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_RECORD.GMT_CREATE
     *
     * @param gmtCreate the value for STAR_RECORD.GMT_CREATE
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_RECORD.GMT_MODIFIED
     *
     * @return the value of STAR_RECORD.GMT_MODIFIED
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_RECORD.GMT_MODIFIED
     *
     * @param gmtModified the value for STAR_RECORD.GMT_MODIFIED
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column STAR_RECORD.STAR_CREATOR
     *
     * @return the value of STAR_RECORD.STAR_CREATOR
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public String getStarCreator() {
        return starCreator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column STAR_RECORD.STAR_CREATOR
     *
     * @param starCreator the value for STAR_RECORD.STAR_CREATOR
     *
     * @mbg.generated Thu May 12 20:58:58 GMT+08:00 2022
     */
    public void setStarCreator(String starCreator) {
        this.starCreator = starCreator == null ? null : starCreator.trim();
    }
}