package com.community.model;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_name
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.token
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.bio
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.avatar_url
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.salt
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    private Integer status;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_id
     *
     * @return the value of user_info.account_id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_id
     *
     * @param accountId the value for user_info.account_id
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_name
     *
     * @return the value of user_info.account_name
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_name
     *
     * @param accountName the value for user_info.account_name
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.token
     *
     * @return the value of user_info.token
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.token
     *
     * @param token the value for user_info.token
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_create
     *
     * @return the value of user_info.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_create
     *
     * @param gmtCreate the value for user_info.gmt_create
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_modified
     *
     * @return the value of user_info.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_modified
     *
     * @param gmtModified the value for user_info.gmt_modified
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.bio
     *
     * @return the value of user_info.bio
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.bio
     *
     * @param bio the value for user_info.bio
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.avatar_url
     *
     * @return the value of user_info.avatar_url
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.avatar_url
     *
     * @param avatarUrl the value for user_info.avatar_url
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.salt
     *
     * @return the value of user_info.salt
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.salt
     *
     * @param salt the value for user_info.salt
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
<<<<<<< HEAD
     * @mbg.generated Fri May 13 21:31:01 GMT+08:00 2022
=======
     * @mbg.generated Fri May 13 21:29:48 CST 2022
>>>>>>> 867e11aaffb7bc5c524c4cf1c8fc98ddf58a8f1e
     */
    public void setStatus(Integer status) {
        this.status = status;
    }
}