package com.community.model;

import java.util.Date;

public class User {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_id
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String accountId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.account_name
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String accountName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.token
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String token;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_create
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private Long gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gmt_modified
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private Long gmtModified;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.bio
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String bio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.avatar_url
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String avatarUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.password
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String password;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.email
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String email;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.salt
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String salt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.status
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.gender
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private Integer gender;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.phone_number
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String phoneNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.qq_number
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String qqNumber;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.birth
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private Date birth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.university
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String university;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.WeChat
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String wechat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_info.type
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_id
     *
     * @return the value of user_info.account_id
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getAccountId() {
        return accountId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_id
     *
     * @param accountId the value for user_info.account_id
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setAccountId(String accountId) {
        this.accountId = accountId == null ? null : accountId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.account_name
     *
     * @return the value of user_info.account_name
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getAccountName() {
        return accountName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.account_name
     *
     * @param accountName the value for user_info.account_name
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setAccountName(String accountName) {
        this.accountName = accountName == null ? null : accountName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.token
     *
     * @return the value of user_info.token
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getToken() {
        return token;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.token
     *
     * @param token the value for user_info.token
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setToken(String token) {
        this.token = token == null ? null : token.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_create
     *
     * @return the value of user_info.gmt_create
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public Long getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_create
     *
     * @param gmtCreate the value for user_info.gmt_create
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setGmtCreate(Long gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gmt_modified
     *
     * @return the value of user_info.gmt_modified
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public Long getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gmt_modified
     *
     * @param gmtModified the value for user_info.gmt_modified
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setGmtModified(Long gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.bio
     *
     * @return the value of user_info.bio
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getBio() {
        return bio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.bio
     *
     * @param bio the value for user_info.bio
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setBio(String bio) {
        this.bio = bio == null ? null : bio.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.avatar_url
     *
     * @return the value of user_info.avatar_url
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getAvatarUrl() {
        return avatarUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.avatar_url
     *
     * @param avatarUrl the value for user_info.avatar_url
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setAvatarUrl(String avatarUrl) {
        this.avatarUrl = avatarUrl == null ? null : avatarUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.password
     *
     * @return the value of user_info.password
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.password
     *
     * @param password the value for user_info.password
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.email
     *
     * @return the value of user_info.email
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.email
     *
     * @param email the value for user_info.email
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.salt
     *
     * @return the value of user_info.salt
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getSalt() {
        return salt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.salt
     *
     * @param salt the value for user_info.salt
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setSalt(String salt) {
        this.salt = salt == null ? null : salt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.status
     *
     * @return the value of user_info.status
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.status
     *
     * @param status the value for user_info.status
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.gender
     *
     * @return the value of user_info.gender
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.gender
     *
     * @param gender the value for user_info.gender
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.phone_number
     *
     * @return the value of user_info.phone_number
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getPhoneNumber() {
        return phoneNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.phone_number
     *
     * @param phoneNumber the value for user_info.phone_number
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber == null ? null : phoneNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.qq_number
     *
     * @return the value of user_info.qq_number
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getQqNumber() {
        return qqNumber;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.qq_number
     *
     * @param qqNumber the value for user_info.qq_number
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setQqNumber(String qqNumber) {
        this.qqNumber = qqNumber == null ? null : qqNumber.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.birth
     *
     * @return the value of user_info.birth
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public Date getBirth() {
        return birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.birth
     *
     * @param birth the value for user_info.birth
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setBirth(Date birth) {
        this.birth = birth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.university
     *
     * @return the value of user_info.university
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getUniversity() {
        return university;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.university
     *
     * @param university the value for user_info.university
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setUniversity(String university) {
        this.university = university == null ? null : university.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.WeChat
     *
     * @return the value of user_info.WeChat
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getWechat() {
        return wechat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.WeChat
     *
     * @param wechat the value for user_info.WeChat
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setWechat(String wechat) {
        this.wechat = wechat == null ? null : wechat.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_info.type
     *
     * @return the value of user_info.type
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_info.type
     *
     * @param type the value for user_info.type
     *
     * @mbg.generated Wed May 25 17:15:12 CST 2022
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}